[package]
name = "rust_client"
version = "0.1.0"
authors = ["dak-x <2018UCS0068@iitjammu.ac.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.7"
rand = "0.7.3"
lazy_static = "1.4.0"
